version: '3.6'

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    # Uncomment below to expose Ollama API outside the container stack
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all

  ollama-webui:
    # build:
    #   context: .
    #   args:
    #     OLLAMA_API_BASE_URL: '/ollama/api'
    #   dockerfile: Dockerfile
    volumes:
      - open-webui:/app/backend/data
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  pgadmin:
    image: elestio/pgadmin:latest
    ports:
      - 8001:8001
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8001
    volumes:
        - documentation-rag-demo-pgadmin:/var/lib/pgadmin

  postgres:
    build:
        context: .
        dockerfile: pgvector.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - documentation-rag-demo-postgres:/var/lib/postgresql/data

volumes:
  ollama: {}
  open-webui: {}
  documentation-rag-demo-pgadmin:
  documentation-rag-demo-postgres:
